name: Build and Test CI

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main

jobs:
  build:
    name: Build do Projeto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn -B package -DskipTests

  test:
    name: Testar o Projeto
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar banco de dados H2 no container
        run:
          docker run -d --name h2db -p 9092:9092 oscarfonts/h2
          sleep 10 # Esperar o container do H2 estar pronto

      - name: Testar com Maven
        run: mvn test
